# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:48
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action')),
                ('table', models.CharField(blank=True, max_length=30, null=True, verbose_name='Table')),
                ('fileds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fields')),
                ('values', models.CharField(blank=True, max_length=255, null=True, verbose_name='Values')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'LogUsers',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Image')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TodoLists',
            },
        ),
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[('Normal', 'Normal'), ('Admin', 'Admin')], default='Normal', max_length=30, verbose_name='type_user')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User TodoLists',
            },
        ),
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertodolist', to='TodoListApi.UserTodo', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='loguser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Logusers', to='TodoListApi.UserTodo', verbose_name='User'),
        ),
    ]
