# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ListsContent',
            },
        ),
        migrations.AddField(
            model_name='todolist',
            name='listcontent',
            field=models.ManyToManyField(blank=True, to='TodoListApi.ListContent', verbose_name='listcontent'),
        ),
    ]
