# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApi', '0002_auto_20171113_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='listcontent',
        ),
        migrations.AddField(
            model_name='listcontent',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolistcontent', to='TodoListApi.TodoList', verbose_name='TodoList'),
        ),
    ]
