# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApi', '0004_auto_20171116_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcontent',
            name='correct',
            field=models.BooleanField(default=False, help_text='Is a correct answer?', verbose_name='Correct'),
        ),
    ]
