# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApi', '0005_listcontent_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcontent',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listcontent', to='TodoListApi.TodoList', verbose_name='TodoList'),
        ),
    ]
